[project]
name = "saealib"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "numpy>=1.22.1",
    "scipy>=1.0.0",
    "typing-extensions>=4.15.0",
]
authors = [
    { name = "shlka", email = "sazakurosulp36@gmail.com" }
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/saealib"]

[tool.uv]
dev-dependencies = [
    "opfunu>=1.0.4",
    "setuptools>=80.9.0",
    "ruff",
]
