[tool.poetry]
name = "saealib"
version = "0.1.0"
description = ""
authors = ["shlka <sazakurosulp36@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.10,<4.0"
numpy = ">=1.22.1"
scipy = ">=1.0.0"


[tool.poetry.group.dev.dependencies]
opfunu = {version = "^1.0.4", python = ">=3.10,<3.12"}
setuptools = "^80.9.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
